invenio_uploadbyurl/__init__.py
# -*- coding: utf-8 -*-
#
# Copyright (C) 2017-2018 HZDR
#
# This file is part of Rodare.
#
# Rodare is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Rodare is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Rodare.  If not, see <http://www.gnu.org/licenses/>.

r"""
Module for invenio for server-side download from a given URL.

The invenio-uploadyburl module for Invenio adds the ability to upload
files from a remote server via the available protocols. Currently, SFTP and
HTTP are implemented. The downloads are performed in asynchronous celery
tasks. The user is notified via Email, once the task is finished or has failed
for some reason.

Alembic
-------

If you wish to add invenio-uploadbyurl to an existing installation, you can
use the provided alembic recipes to migrate your database.

In general you need to invoke the following command to migrate your db:

.. code-block:: python

    invenio alembic upgrade heads

Further information is available in the documentation of
`Invenio-DB <https://invenio-db.readthedocs.io/en/latest/alembic.html>`_.

Initialization
--------------

For using the SFTP background upload you need to register remote servers
first. If you wish to register the server with the address
``sftp1.test.de`` accessible on port 22, execute the following lines of code
in the application context:

.. code-block:: python

    from invenio_db import db
    from invenio_uploadbyurl.models import RemoteServer

    remote = RemoteServer(
        name='sftp1',
        server_address='sftp1.test.de',
        port=22,
        description='SFTP test server.',
    )
    db.session.add(remote)
    db.session.commit()

Before you try to connect to the registered RemoteServers, make sure that the
RemoteServer's host key is added to the system host keys of your operating
system. Otherwise, all connection attempts will fail.

Customization
-------------

For some SFTP servers it might be necessary to overwrite the default functions
for e.g. key deployment. It can be configured by specifing the configuration
variable ``UPLOADBYURL_REMOTE_SERVERS``.

Example
^^^^^^^
.. code-block:: python

    UPLOADBYURL_REMOTE_SERVERS = {
        'mysftp': {
            'deploy_handler': 'mymodule.utils:deploy_ssh_key',
            'delete_handler': 'mymodule.utils:delete_ssh_key',
        }
    }

More customization options are planned for future releases.

REST API
--------

Background uploads can be triggered via the REST API. Many operations operate
on a bucket, defined by
`Invenio-Files-REST  <https://invenio-files-rest.readthedocs.io/
en/latest/index.html>`_.
For the operations presented here, it is required to connect the user account
with the remote server before. You are also required to be authenticated.

Let's assume the bucket we operate on has the UUID defined in the variable
bucket:

.. code-block:: bash

    $ export BUCKET=11111111-1111-1111-1111-111111111111

Furthermore the remote server with the name ``sftp1`` is registered.

.. code-block:: bash

    $ export SERVER_NAME=11111111-1111-1111-1111-111111111111

The following REST API endpoints can then be used.

File Browsing
^^^^^^^^^^^^^

Browse root directory of remote server ``sftp1``:

.. code-block:: bash

    curl -X POST http://localhost:5000/uploadbyurl/browse/$SERVER_NAME

The response could look similar to the following JSON object:

.. literalinclude:: static/browse.json
    :language: json

By adding the path parameter you can browse a specific directory, e.g.:

.. code-block:: bash

    curl -X POST http://localhost:5000/uploadbyurl/browse/sftp1?path=%2Fhome

and receive a similar json response. The file browsing results are cached for
300s to reduce the amount of traffic on the remote servers.

SFTP background upload
^^^^^^^^^^^^^^^^^^^^^^

Background uploads via SFTP can be triggered via the REST API. Let's assume
we wish to upload the file ``/home/foo/foo``. Therefore, the following request
needs to be performed:

.. code-block:: bash

    $ curl -X POST http://localhost:5000/uploadbyurl/$BUCKET/ \\
        $SERVER_NAME?path=/home/foo/foo

Upload via URL
^^^^^^^^^^^^^^

Uploading via URL can be triggered via an HTTP request, too:

.. code-block:: bash

    $ curl -X POST http://localhost:5000/uploadbyurl/$BUCKET \\
        ?url=http://ipv4.download.thinkbroadband.com/5MB.zip

"""

from .ext import InvenioUploadByURL
from .proxies import current_uploadbyurl
from .version import __version__

__all__ = (
    '__version__',
    'current_uploadbyurl',
    'InvenioUploadByURL',
)

invenio_uploadbyurl/views/__init__.py
# -*- coding: utf-8 -*-
#
# Copyright (C) 2017-2018 HZDR
#
# This file is part of Rodare.
#
# Rodare is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Rodare is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Rodare.  If not, see <http://www.gnu.org/licenses/>.

"""Blueprints for uploadbyurl."""

from .settings import blueprint as settings_blueprint

blueprints = [
    settings_blueprint,
]

invenio_uploadbyurl/views/settings.py
# -*- coding: utf-8 -*-
#
# Copyright (C) 2017-2018 HZDR
#
# This file is part of Rodare.
#
# Rodare is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Rodare is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Rodare.  If not, see <http://www.gnu.org/licenses/>.

"""Account settings blueprint for invenio-uploadbyurl."""

import json
from datetime import datetime

import celery.states
from celery.result import AsyncResult
from flask import Blueprint, abort, current_app, redirect, render_template, \
    request, url_for
from flask_babelex import gettext as _
from flask_breadcrumbs import register_breadcrumb
from flask_login import current_user, login_required
from flask_menu import register_menu
from werkzeug.local import LocalProxy

from ..errors import RemoteServerNotFoundError
from ..forms import ConnectForm
from ..models import RemoteServer, SSHKey
from ..proxies import current_uploadbyurl
from ..utils import connect_user_and_server, create_cache_key, \
    delete_ssh_key, generate_public_keystr

_redisstore = LocalProxy(
    lambda: current_app.extensions['invenio-uploadbyurl'].redisstore)

blueprint = Blueprint(
    'invenio_uploadbyurl_settings',
    __name__,
    url_prefix='/account/settings/remoteserver',
    static_folder='../static',
    template_folder='../templates',
)


@blueprint.record_once
def post_ext_init(state):
    """Set necessary config."""
    app = state.app

    app.config.setdefault(
        "UPLOADBYURL_SETTINGS_TEMPLATE",
        app.config.get("SETTINGS_TEMPLATE",
                       "invenio_uploadbyurl/settings/base.html"))


@blueprint.route('/', methods=['GET', 'POST'])
@login_required
@register_menu(
    blueprint, 'settings.uploadbyurl',
    _('%(icon)s Remote Server', icon='<i class="fa fa-server fa-fw"></i>'),
    order=15,
    active_when=lambda: request.endpoint.startswith(
        'invenio_uploadbyurl_settings'),
    visible_when=lambda: bool(current_app.config.get(
        'UPLOADBYURL_ACTIVATE')) is not False
)
@register_breadcrumb(
    blueprint, 'breadcrumbs.settings.uploadbyurl', _('Remote Server')
)
def index():
    """List available remote servers."""
    remote_servers = RemoteServer.all()

    # check if user is already connected
    for remote in remote_servers:
        key = SSHKey.get(current_user.id, remote.id)
        remote.connected = True if key else False
        remote.pub_key = generate_public_keystr(key) if key else None

    # Find recent background jobs
    try:
        key = create_cache_key(current_user.id)
        data = _redisstore.get(key)
        job_list = json.loads(data.decode('utf-8'))
    except KeyError:
        job_list = []

    # sort job_list by date
    job_list.sort(key=lambda x: x['created'], reverse=True)

    for job in job_list:
        res = AsyncResult(job['celery_id'])
        if res.state in celery.states.PROPAGATE_STATES:
            job['state'] = 'FAILURE'
        elif res.state == celery.states.STARTED:
            job['state'] = 'STARTED'
        elif res.state in celery.states.UNREADY_STATES:
            job['state'] = 'PENDING'
        else:
            job['state'] = 'SUCCESS'

        job['created'] = datetime.fromtimestamp(job['created'])

    return render_template(
        'invenio_uploadbyurl/settings/index.html',
        remote_servers=remote_servers,
        formclass=ConnectForm,
        job_list=job_list,
    )


@blueprint.route('/init/<remote_name>', methods=['GET', 'POST'])
@login_required
def init(remote_name):
    """Initialiaze connection to remote server."""
    remote = RemoteServer.get_by_name(remote_name)
    if not remote:
        raise RemoteServerNotFoundError()
    connect_form = ConnectForm()

    if connect_form.validate_on_submit():
        username = connect_form.username.data
        password = connect_form.password.data
        connect_user_and_server(remote, username, password)
        return redirect(url_for('invenio_uploadbyurl_settings.index'))

    return render_template(
        'invenio_uploadbyurl/settings/init.html',
        remote=remote,
        connect_form=connect_form,
    )


@blueprint.route('/delete/<remote_name>', methods=['GET', 'POST'])
@login_required
def delete(remote_name):
    """Delete connection with remote server for current user."""
    remote = RemoteServer.get_by_name(remote_name)
    if not remote:
        raise RemoteServerNotFoundError()
    current_uploadbyurl.delete_handler.get(remote.name, delete_ssh_key)(remote)
    return redirect(url_for('invenio_uploadbyurl_settings.index'))

invenio_uploadbyurl/templates/invenio_uploadbyurl/settings/base.html
{# -*- coding: utf-8 -*-
#
# This file is part of RODARE.
# Copyright (C) 2017 HZDR.
#
# RODARE is free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of the
# License, or (at your option) any later version.
#
# RODARE is distributed in the hope that it will be
# useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with RODARE; if not, write to the
# Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston,
# MA 02111-1307, USA.
#}
{%- extends "invenio_uploadbyurl/base.html" %}

{%- block page_body %}
{%- block settings_content %}
{%- block settings_body %}{%- endblock settings_body %}
{%- endblock settings_content %}
{%- endblock page_body %}

invenio_uploadbyurl/templates/invenio_uploadbyurl/settings/helpers.html
{%- macro panel_start(title, icon="", id="", with_body=True, panel_extra_class="panel-default") %}
{%- block panel_start scoped %}
<div class="panel-group panel-bot-margin"{% if id %} id="{{id}}"{% endif %}>
    <div class="panel {{panel_extra_class}}">
        {%- block panel_heading scoped %}
        <div class="panel-heading">
            <strong>{%if icon %}<i class="{{icon}}"></i>{% endif %} {{title}}</strong>
        </div>
        {%- endblock %}
        {%- if with_body %}
        <div class="panel-body">
        {%- endif %}
{%- endblock %}
{%- endmacro %}

{%- macro panel_end(with_body=True) %}
{%- block panel_end scoped %}
        {%- if with_body %}
        </div>
        {%- endif %}
    </div>
</div>
{%- endblock %}
{%- endmacro %}

invenio_uploadbyurl/templates/invenio_uploadbyurl/settings/index.html
{# -*- coding: utf-8 -*-
#
# This file is part of RODARE.
# Copyright (C) 2017 HZDR.
#
# RODARE is free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of the
# License, or (at your option) any later version.
#
# RODARE is distributed in the hope that it will be
# useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with RODARE; if not, write to the
# Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston,
# MA 02111-1307, USA.
#}
{%- import "invenio_uploadbyurl/settings/helpers.html" as helpers with context %}

{%- extends config.UPLOADBYURL_SETTINGS_TEMPLATE %}

{% set panel_title = _("Remote servers") %}
{% set panel_icon = "fa fa-server" %}

{%- block javascript %}
  {% assets "invenio_uploadbyurl_dependencies_js" %}<script src="{{ ASSET_URL }}"></script>{% endassets %}
  {% assets "invenio_uploadbyurl_js" %}<script src="{{ ASSET_URL }}"></script>{% endassets %}
{%- endblock javascript %}

{% block settings_content %}
{{ helpers.panel_start(
  _('Remote servers'),
  with_body=False,
  icon="fa fa-server"
) }}
<div class="panel-body">
    {% block uploadbyurl_body_text %}
    <p>{{ _('You have files on a remote server and wish to import them to RODARE. Connect your account here:') }}</p>
    {% endblock uploadbyurl_body_text %}
</div>
<ul class="list-group">
    {%- for rs in remote_servers %}
    <li class="list-group-item">
      {% block uploadbyurl_control scoped %}
      <div class="pull-right">
          {% if rs.connected %}
          <a href="{{ url_for('invenio_uploadbyurl_settings.delete', remote_name=rs.name) }}" class="btn btn-danger btn-xs"><i class="fa fa-times-circle"></i> {{ _('Disconnect') }}</a>
          {%- else -%}
          <a href="{{ url_for('invenio_uploadbyurl_settings.init', remote_name=rs.name) }}" class="btn btn-success btn-xs"><i class="fa fa-plug"></i> {{ _('Connect') }}</a>
          {%- endif -%}
      </div>
      {% endblock uploadbyurl_control %}
      <i class="fa fa-server"></i>
      &nbsp;{{ rs.name }}
      <span class="label label-info" data-toggle="tooltip" title="{{ rs.description }}">{{rs.server_address}}</span>
      {% if rs.connected %}<i class="fa fa-check text-success" data-toggle="tooltip" title="{{ _('Your account and the remote server are connected.') }}"></i>{% endif %}
      {% if rs.pub_key %}
      <p>
        <div class="input-group input-group-sm">
          <span class="input-group-addon" id="key_descr"><i class="fa fa-key" aria-hidden="true"></i>&nbsp {{ _('SSH Public key') }}</span>
          <input type="text" id="pub-key-{{ rs.name }}" value="{{ rs.pub_key }}" class="form-control" aria-describedby="key_descr" readonly>
          <span class="input-group-btn">
            <button class="btn btn-default" data-clipboard-target="#pub-key-{{ rs.name }}" type="button" aria-label="Copy SSH public key"><i class="fa fa-clipboard" aria-hidden="true"></i></button>
          </span>
        </div>
      </p>
      {% endif %}
    </li>
    {%- endfor %}
</ul>
{{ helpers.panel_end(with_body=False) }}

{% if job_list %}
{% block uploadbyurl_status %}
{{ helpers.panel_start(
  _('Recent background jobs'),
  with_body=False,
  icon="fa fa-server"
) }}
<div class="panel-body">
  <p>During the last {{ config.UPLOADBYURL_CACHE_DURATION }} days you started these background upload jobs.</p>
</div>
<div class="list-group">
  {% for job in job_list %}
  {% if job.state == 'SUCCESS' %}
    {% set status_icon = 'fa-check-circle text-success' %}
  {% elif job.state == 'PENDING' %}
    {% set status_icon = 'fa-pause-circle text-warning' %}
  {% elif job.state == 'FAILURE' %}
    {% set status_icon = 'fa-times-circle text-danger' %}
  {% elif job.state == 'STARTED' %}
    {% set status_icon = 'fa-play-circle text-primary' %}
  {% else %}
    {% set status_icon = 'fa-question-circle text-secondary' %}
  {% endif %}
  <a class="list-group-item">
    <div class="row" data-toggle="tooltip" title="{{ job.state }}">
      <div class="col-xs-1">
        <i class="fa {{ status_icon }} fa-2x"></i>
      </div>
      <div class="col-xs-11" style="overflow: hidden; white-space: nowrap; text-overflow:ellipsis;">
          <strong>{{ job.location }}</strong>
          <small>
            <br><strong>Created:</strong> {{ job.created | tousertimezone | datetimeformat }}
            <br><strong>Job ID:</strong> {{ job.celery_id }}
            <br><strong>Bucket ID:</strong> {{ job.bucket_id }}
            <br><strong>Protocol:</strong> {{ job.protocol }}
          </small>
        </div>
    </div>
  </a>
  {% endfor %}
</div>
{{ helpers.panel_end(with_body=False) }}
{% endblock uploadbyurl_status %}
{% else %}
{% block advertize_uploadbyurl %}
{{ helpers.panel_start(
  _('Recent background jobs'),
  icon="fa fa-server"
) }}
<div class="row" align="center">
  <div class="container">
    <h2>Create a new record to see the job status!</h2>
    <p>
      <a href="{{ url_for('invenio_deposit_ui.new') }}" class="btn btn-default btn-lg">
        <i class="fa fa-cloud-upload" aria-hidden="true"></i> New Upload
      </a>
    </p>
    <p class="text-muted">
      To use Background Upload via SFTP you need to connect your account first. Click <strong>Connect</strong> and follow the steps.
    </p>
  </div>
</div>
{{ helpers.panel_end() }}
{% endblock advertize_uploadbyurl %}
{% endif %}
{% endblock settings_content %}

invenio_uploadbyurl/templates/invenio_uploadbyurl/settings/init.html
{# -*- coding: utf-8 -*-
#
# This file is part of RODARE.
# Copyright (C) 2017 HZDR.
#
# RODARE is free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of the
# License, or (at your option) any later version.
#
# RODARE is distributed in the hope that it will be
# useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with RODARE; if not, write to the
# Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston,
# MA 02111-1307, USA.
#}
{%- extends config.UPLOADBYURL_SETTINGS_TEMPLATE %}

{% from "invenio_uploadbyurl/_macros.html" import render_field %}

{% set panel_title = _("Remote servers") %}
{% set panel_icon = "fa fa-server" %}

{% block settings_body %}
<div class="panel-body">
    {% block uploadbyurl_body_text %}
    {% endblock uploadbyurl_body_text %}
    {% block uploadbyurl_security_form %}
    {%- with form = connect_form %}
    <div class="well col-md-6 col-md-offset-3">
        <h4>{{ _('Connect to %(remote_name)s server:', remote_name=remote.name)}}</h4>
        <p>{{ _('We do not store your password. It is required to connect to the remote machine once and transfer an SSH key.') }}</p>
        <form action="{{url_for('invenio_uploadbyurl_settings.init', remote_name=remote.name)}}" method="POST">
            {{ form.csrf_token }}
            {{ render_field(form.username, icon="fa fa-user", autofocus=True) }}
            {{ render_field(form.password, icon="fa fa-unlock") }}
            <button type="submit" class="btn btn-primary btn-block btn-lg" title="{{remote.server_address}}">
                <i class="fa fa-plug" aria-hidden="true"></i> {{ _('Connect') }}
            </button>
        </form>
    </div>
    {% endwith %}
    {% endblock uploadbyurl_security_form %}
</div>
{% endblock settings_body %}